# Generated by Django 4.1 on 2022-08-28 12:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='img/profile_pictures', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображении',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1111111111), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=20, null=True, verbose_name='Электровнная почта')),
                ('verification', models.BooleanField(default=False, verbose_name='Верефикация')),
                ('avatar', models.ImageField(default=None, upload_to='img/avatar', verbose_name='Фотография профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время публикации')),
                ('comment', models.ManyToManyField(blank=True, related_name='posts', to='webcam.comment', verbose_name='Коментарий')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcam.picture', verbose_name='Изображение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcam.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcam.profile', verbose_name='Пользователь'),
        ),
    ]
