# Generated by Django 4.1 on 2022-09-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0002_imagefilter_alter_profile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagefilter',
            options={'verbose_name': 'Фильтр', 'verbose_name_plural': 'Фильтры для снимков'},
        ),
        migrations.AddField(
            model_name='imagefilter',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название маски'),
        ),
    ]
